# Bonsai 1-bit LLM Setup Script
# Requires: Windows 10/11, NVIDIA GPU with CUDA 13.x, PowerShell 5+

param(
    [string]$InstallDir = "C:\1bitllm",
    [ValidateSet("8B", "4B", "1.7B")]
    [string]$ModelSize = "8B",
    [ValidateSet("13.1", "12.4")]
    [string]$CudaVersion = "13.1",
    [int]$Port = 8080
)

$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"

$RELEASE_TAG = "prism-b8196-f5dda72"
$RELEASE_BASE = "https://github.com/PrismML-Eng/llama.cpp/releases/download/$RELEASE_TAG"

$ModelUrls = @{
    "8B"   = "https://huggingface.co/prism-ml/Bonsai-8B-gguf/resolve/main/Bonsai-8B.gguf"
    "4B"   = "https://huggingface.co/prism-ml/Bonsai-4B-gguf/resolve/main/Bonsai-4B.gguf"
    "1.7B" = "https://huggingface.co/prism-ml/Bonsai-1.7B-gguf/resolve/main/Bonsai-1.7B.gguf"
}

$CudaTag = $CudaVersion -replace "\.", "."
$BinsUrl   = "$RELEASE_BASE/llama-prism-b1-f5dda72-bin-win-cuda-$CudaTag-x64.zip"
$CudartUrl = "$RELEASE_BASE/cudart-llama-bin-win-cuda-$CudaTag-x64.zip"
$ModelUrl  = $ModelUrls[$ModelSize]
$ModelFile = "Bonsai-$ModelSize.gguf"

function Write-Step($msg) {
    Write-Host ""
    Write-Host "==> $msg" -ForegroundColor Cyan
}

function Get-FileSize($bytes) {
    if ($bytes -ge 1GB) { "{0:N1} GB" -f ($bytes / 1GB) }
    elseif ($bytes -ge 1MB) { "{0:N0} MB" -f ($bytes / 1MB) }
    else { "{0:N0} KB" -f ($bytes / 1KB) }
}

function Download-File($url, $dest, $label) {
    Write-Host "  Downloading $label..." -NoNewline
    $start = Get-Date
    Invoke-WebRequest -Uri $url -OutFile $dest -UseBasicParsing
    $elapsed = ((Get-Date) - $start).TotalSeconds
    $size = Get-FileSize (Get-Item $dest).Length
    Write-Host " done ($size in $([math]::Round($elapsed, 1))s)" -ForegroundColor Green
}

# ── Banner ────────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "  Bonsai 1-bit LLM Installer" -ForegroundColor Yellow
Write-Host "  Model: Bonsai-$ModelSize  |  CUDA: $CudaVersion  |  Port: $Port"
Write-Host "  Install dir: $InstallDir"
Write-Host ""

# ── Preflight ─────────────────────────────────────────────────────────────────
Write-Step "Checking prerequisites"

if (-not (Get-Command nvidia-smi -ErrorAction SilentlyContinue)) {
    Write-Host "  WARNING: nvidia-smi not found. GPU offload may not work." -ForegroundColor Yellow
} else {
    $gpu = (nvidia-smi --query-gpu=name,memory.total --format=csv,noheader) -join ", "
    Write-Host "  GPU: $gpu" -ForegroundColor Green
}

# ── Directories ───────────────────────────────────────────────────────────────
Write-Step "Creating directories"
$binDir   = Join-Path $InstallDir "bin"
$modelDir = Join-Path $InstallDir "models"
$tmpDir   = Join-Path $InstallDir "tmp"
New-Item -ItemType Directory -Force -Path $binDir, $modelDir, $tmpDir | Out-Null
Write-Host "  $InstallDir" -ForegroundColor Green

# ── Download binaries ─────────────────────────────────────────────────────────
Write-Step "Downloading llama.cpp binaries (CUDA $CudaVersion)"
$binsZip   = Join-Path $tmpDir "llama-bins.zip"
$cudartZip = Join-Path $tmpDir "cudart.zip"

Download-File $BinsUrl   $binsZip   "llama.cpp executables"
Download-File $CudartUrl $cudartZip "CUDA runtime DLLs"

# ── Extract ───────────────────────────────────────────────────────────────────
Write-Step "Extracting binaries"
Expand-Archive -Path $binsZip   -DestinationPath $binDir -Force
Expand-Archive -Path $cudartZip -DestinationPath $binDir -Force
Write-Host "  Extracted to $binDir" -ForegroundColor Green

# ── Download model ────────────────────────────────────────────────────────────
Write-Step "Downloading Bonsai-$ModelSize model"
$modelPath = Join-Path $modelDir $ModelFile

if (Test-Path $modelPath) {
    Write-Host "  Model already exists, skipping download." -ForegroundColor Yellow
} else {
    Download-File $ModelUrl $modelPath "Bonsai-$ModelSize GGUF"
}

# ── Write run script ──────────────────────────────────────────────────────────
Write-Step "Writing run script"
$runScript = Join-Path $InstallDir "run.ps1"
@"
# Run Bonsai $ModelSize — generated by install.ps1
`$bin   = "$binDir\llama-server.exe"
`$model = "$modelDir\$ModelFile"
`$port  = $Port

Write-Host "Starting Bonsai-$ModelSize on http://localhost:`$port" -ForegroundColor Cyan
Write-Host "Press Ctrl+C to stop.`n"
& `$bin -m `$model -ngl 99 --ctx-size 65536 --port `$port
"@ | Set-Content $runScript -Encoding UTF8
Write-Host "  $runScript" -ForegroundColor Green

# ── Cleanup ───────────────────────────────────────────────────────────────────
Write-Step "Cleaning up temp files"
Remove-Item $tmpDir -Recurse -Force
Write-Host "  Done" -ForegroundColor Green

# ── Done ──────────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "  Installation complete!" -ForegroundColor Yellow
Write-Host ""
Write-Host "  To start the server, run:" -ForegroundColor White
Write-Host "    powershell -ExecutionPolicy Bypass -File `"$runScript`"" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Then open http://localhost:$Port in your browser." -ForegroundColor White
Write-Host ""
